# darkflow:start
# Dark Flow — managed block. Regenerated by install.sh/update.sh. Do not edit between the markers.
.PHONY: df-help df-run df-sync df-force-install

df-help:  ## Dark Flow: list available df-* targets
	@grep -E '^df-[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort \
	  | awk 'BEGIN{FS=":.*?## "}{printf "  \033[36m%-26s\033[0m %s\n",$$1,$$2}'

df-run:  ## run the routine dispatcher loop (every 60s)
	bash .darkflow.d/darkflow-run.sh

df-sync:  ## push GitHub issues + project metadata to the web UI
	bash .darkflow.d/darkflow-run.sh --sync

df-force-install:  ## force-reinstall Dark Flow from remote (overwrites templates)
	bash <(curl -fsSL https://raw.githubusercontent.com/alifanov/darkflow/main/install.sh) --force --yes
# darkflow:end
