# darkflow:start
# Dark Flow — managed block. Regenerated by install.sh/update.sh. Do not edit between the markers.
.PHONY: df-help df-list df-sync df-force-install

df-help:  ## Dark Flow: list available df-* targets
	@grep -E '^df-[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort \
	  | awk 'BEGIN{FS=":.*?## "}{printf "  \033[36m%-26s\033[0m %s\n",$$1,$$2}'

df-list:  ## show this project's routine status (the global worker runs them automatically)
	~/.darkflow/darkflow-run.sh --list

df-sync:  ## push this project's GitHub issues + metadata to the web UI
	~/.darkflow/darkflow-run.sh --sync

df-force-install:  ## force-reinstall Dark Flow from remote (overwrites templates)
	bash <(curl -fsSL https://raw.githubusercontent.com/alifanov/darkflow/main/install.sh) --force --yes
# darkflow:end
