import { Navbar } from "@/components/landing/navbar";
import { Footer } from "@/components/landing/footer";
import type { Metadata } from "next";
import { MARKETING_VIEWPORT } from "@/lib/marketing-viewport";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — ScopeGate",
  description: "The terms and conditions governing your use of ScopeGate.",
  alternates: { canonical: "https://scopegate.dev/terms" },
  robots: { index: false, follow: false },
};

export const viewport = MARKETING_VIEWPORT;

const SECTIONS = [
  {
    title: "1. Acceptance of Terms",
    content: [
      {
        text: 'By creating an account or using the ScopeGate service (the "Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Service.',
      },
    ],
  },
  {
    title: "2. Description of Service",
    content: [
      {
        text: "ScopeGate is an AI Access Proxy Layer that allows users to connect external services, define granular permissions, and expose a Model Context Protocol (MCP) endpoint for use with AI agents. The Service is provided on a subscription basis with a free tier available.",
      },
    ],
  },
  {
    title: "3. Eligibility",
    content: [
      {
        text: "You must be at least 16 years old and capable of forming a binding contract to use the Service. By using the Service, you represent and warrant that you meet these requirements.",
      },
    ],
  },
  {
    title: "4. Account Responsibilities",
    content: [
      {
        subtitle: "Account security",
        text: "You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. Notify us immediately at security@scopegate.dev if you suspect unauthorised access.",
      },
      {
        subtitle: "Accurate information",
        text: "You agree to provide accurate, current, and complete information during registration and to keep this information updated.",
      },
      {
        subtitle: "One account per person",
        text: "Each natural person may maintain only one free account. Additional accounts may be permitted under enterprise plans.",
      },
    ],
  },
  {
    title: "5. Acceptable Use",
    content: [
      {
        subtitle: "Permitted use",
        text: "You may use the Service only for lawful purposes and in accordance with these Terms. The Service is designed to act as a permission proxy between your AI agents and third-party services you are authorised to access.",
      },
      {
        subtitle: "Prohibited conduct",
        text: "You must not: (a) use the Service to access third-party services without proper authorisation; (b) attempt to reverse-engineer, decompile, or extract source code; (c) use the Service to transmit malware or engage in denial-of-service attacks; (d) resell or sublicense the Service without our written consent; (e) circumvent rate limits or security controls; or (f) use the Service in any way that violates applicable law.",
      },
    ],
  },
  {
    title: "6. API Keys and MCP Endpoints",
    content: [
      {
        subtitle: "API key security",
        text: "API keys generated by the Service grant access to your MCP endpoints. You are solely responsible for keeping your API keys confidential. We are not liable for any damage resulting from unauthorised use of your API keys.",
      },
      {
        subtitle: "Key revocation",
        text: "You may regenerate or revoke API keys at any time from the dashboard. Regenerating a key immediately invalidates the previous key.",
      },
    ],
  },
  {
    title: "7. Third-Party Services",
    content: [
      {
        text: "The Service facilitates connections to third-party services (e.g., Google, LinkedIn). Your use of those services is governed by their respective terms and privacy policies. ScopeGate is not affiliated with, endorsed by, or responsible for those third-party services.",
      },
    ],
  },
  {
    title: "8. Billing and Payments",
    content: [
      {
        subtitle: "Subscription plans",
        text: "Paid plans are billed monthly or annually in advance. All fees are stated in US dollars and are non-refundable except as required by law or as described in our refund policy.",
      },
      {
        subtitle: "Free tier",
        text: "The free tier is provided as-is with no uptime guarantees. We reserve the right to modify the features included in the free tier at any time with 30 days' notice.",
      },
      {
        subtitle: "Payment failure",
        text: "If a payment fails, we will notify you by email. After a 7-day grace period, your account may be downgraded to the free tier and paid features disabled until payment is resolved.",
      },
    ],
  },
  {
    title: "9. Intellectual Property",
    content: [
      {
        subtitle: "Our IP",
        text: 'ScopeGate and the Service, including all software, designs, trademarks, and content, are owned by or licensed to us. The open-core components of the software are available under the MIT licence at github.com/alifanov/scopegate ("Open-Core Components").',
      },
      {
        subtitle: "Your content",
        text: "You retain ownership of any content or configuration you create within the Service. You grant us a limited licence to store and process this content solely to provide the Service.",
      },
    ],
  },
  {
    title: "10. Disclaimers",
    content: [
      {
        text: 'THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF HARMFUL COMPONENTS.',
      },
    ],
  },
  {
    title: "11. Limitation of Liability",
    content: [
      {
        text: "TO THE MAXIMUM EXTENT PERMITTED BY LAW, OUR TOTAL LIABILITY TO YOU FOR ANY CLAIMS ARISING FROM OR RELATED TO THE SERVICE SHALL NOT EXCEED THE GREATER OF (A) THE AMOUNTS PAID BY YOU TO US IN THE 12 MONTHS PRIOR TO THE CLAIM, OR (B) US $50. IN NO EVENT SHALL WE BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES.",
      },
    ],
  },
  {
    title: "12. Indemnification",
    content: [
      {
        text: "You agree to indemnify and hold harmless ScopeGate and its officers, directors, employees, and agents from any claims, damages, losses, or expenses (including reasonable legal fees) arising from your use of the Service, your violation of these Terms, or your violation of any third-party rights.",
      },
    ],
  },
  {
    title: "13. Termination",
    content: [
      {
        subtitle: "By you",
        text: "You may delete your account at any time from the Settings page. Deletion is effective immediately and account data is permanently removed within 30 days.",
      },
      {
        subtitle: "By us",
        text: "We may suspend or terminate your account immediately if you violate these Terms, engage in fraudulent activity, or if required by law. We will attempt to provide advance notice where practicable.",
      },
    ],
  },
  {
    title: "14. Changes to These Terms",
    content: [
      {
        text: "We may update these Terms from time to time. We will notify you by email at least 14 days before material changes take effect. Continued use of the Service after the effective date constitutes your acceptance of the updated Terms.",
      },
    ],
  },
  {
    title: "15. Governing Law",
    content: [
      {
        text: "These Terms are governed by and construed in accordance with the laws of the jurisdiction in which ScopeGate is registered, without regard to conflict of law principles. Any disputes shall be resolved exclusively in the competent courts of that jurisdiction.",
      },
    ],
  },
  {
    title: "16. Contact",
    content: [
      {
        text: "For questions about these Terms, contact us at legal@scopegate.dev.",
      },
    ],
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 overflow-x-hidden">
      <Navbar />

      <main className="max-w-3xl mx-auto px-6 pt-32 pb-24">
        {/* Header */}
        <div className="mb-12">
          <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-medium bg-violet-500/10 text-violet-400 border border-violet-500/20 mb-4">
            Legal
          </span>
          <h1 className="text-3xl sm:text-4xl font-bold text-slate-100 tracking-tight mb-3">
            Terms of Service
          </h1>
          <p className="text-slate-500 text-sm">
            Effective date: <span className="text-slate-400">March 2, 2026</span>
          </p>
          <p className="mt-4 text-slate-400 leading-relaxed">
            Please read these Terms carefully before using ScopeGate. They form a
            legally binding agreement between you and ScopeGate.
          </p>
        </div>

        {/* Sections */}
        <div className="space-y-10">
          {SECTIONS.map((section) => (
            <section key={section.title}>
              <h2 className="text-lg font-semibold text-slate-200 mb-4 pb-2 border-b border-slate-800">
                {section.title}
              </h2>
              <div className="space-y-4">
                {section.content.map((item) => (
                  <div key={item.text.slice(0, 40)}>
                    {"subtitle" in item && item.subtitle && (
                      <h3 className="text-sm font-medium text-slate-300 mb-1">
                        {item.subtitle}
                      </h3>
                    )}
                    <p className="text-sm text-slate-500 leading-relaxed">{item.text}</p>
                  </div>
                ))}
              </div>
            </section>
          ))}
        </div>

        {/* Bottom nav */}
        <div className="mt-16 pt-8 border-t border-slate-800/60 flex flex-col sm:flex-row gap-4 sm:items-center justify-between text-sm">
          <p className="text-slate-600">
            Questions?{" "}
            <a href="mailto:legal@scopegate.dev" className="text-violet-400 hover:text-violet-300 transition-colors">
              legal@scopegate.dev
            </a>
          </p>
          <Link href="/privacy" className="text-slate-500 hover:text-slate-300 transition-colors">
            ← Privacy Policy
          </Link>
        </div>
      </main>

      <Footer />
    </div>
  );
}
